from __future__ import annotations

import logging
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import sync_playwright

from config import BROWSER_PROFILE_DIR, RUNTIME_ENV_PATH, load_config

LOGIN_URL = "https://claude.ai/login"
USAGE_URL = "https://claude.ai/settings/usage"

# These cookies are sufficient for API calls in typical sessions.
PRIMARY_COOKIE_NAMES = (
    "sessionKey",
    "routingHint",
    "lastActiveOrg",
    "anthropic-device-id",
    "ajs_anonymous_id",
)


class AuthTimeoutError(RuntimeError):
    pass


def interactive_login_and_save_config(logger: logging.Logger, reason: str) -> dict[str, str]:
    logger.info("Starting headed login flow (%s)", reason)
    config = load_config()

    with sync_playwright() as p:
        context = _launch_auth_browser(p, config.auth_browser, logger)

        page = context.pages[0] if context.pages else context.new_page()
        page.goto(LOGIN_URL, wait_until="domcontentloaded")

        logger.info("Please complete login in the opened browser window.")
        auth_data = _wait_until_authenticated(context, page, logger=logger)

        _write_runtime_env(auth_data)
        logger.info("Auth data saved to %s", RUNTIME_ENV_PATH)

        context.close()

    return auth_data


def _wait_until_authenticated(
    context: Any, page: Any, logger: logging.Logger, timeout_seconds: int = 600
) -> dict[str, str]:
    deadline = time.monotonic() + timeout_seconds
    visited_usage_after_login = False

    while time.monotonic() < deadline:
        cookies = context.cookies("https://claude.ai")
        cookie_map = {cookie["name"]: cookie["value"] for cookie in cookies}

        has_session = bool(cookie_map.get("sessionKey"))
        org_id = cookie_map.get("lastActiveOrg")

        if has_session and org_id:
            return _extract_auth_data(cookie_map)

        # Avoid aggressive reload loops while Cloudflare/login is in progress.
        # If session exists but org cookie is missing, visit usage once to let app set org context.
        if has_session and not org_id and not visited_usage_after_login:
            try:
                page.goto(USAGE_URL, wait_until="domcontentloaded", timeout=30000)
                visited_usage_after_login = True
            except PlaywrightTimeoutError:
                logger.warning("Timed out opening usage page during auth bootstrap, retrying...")

        time.sleep(2)

    raise AuthTimeoutError(
        "Timed out waiting for login. Please rerun and complete authentication in the browser window."
    )


def _extract_auth_data(cookie_map: dict[str, str]) -> dict[str, str]:
    ordered_cookies: list[str] = []

    for name in PRIMARY_COOKIE_NAMES:
        value = cookie_map.get(name)
        if value:
            ordered_cookies.append(f"{name}={value}")

    # Include additional cookies to reduce chance of missing required context in stricter sessions.
    for name, value in cookie_map.items():
        if name in PRIMARY_COOKIE_NAMES:
            continue
        if value:
            ordered_cookies.append(f"{name}={value}")

    return {
        "CLAUDE_ORG_ID": cookie_map["lastActiveOrg"],
        "CLAUDE_COOKIE_HEADER": "; ".join(ordered_cookies),
        "ANTHROPIC_DEVICE_ID": cookie_map.get("anthropic-device-id", ""),
        "ANTHROPIC_ANONYMOUS_ID": cookie_map.get("ajs_anonymous_id", ""),
    }


def _write_runtime_env(values: dict[str, str]) -> None:
    Path(RUNTIME_ENV_PATH).parent.mkdir(parents=True, exist_ok=True)

    existing: dict[str, str] = {}
    if Path(RUNTIME_ENV_PATH).exists():
        for line in Path(RUNTIME_ENV_PATH).read_text(encoding="utf-8").splitlines():
            if not line or line.strip().startswith("#") or "=" not in line:
                continue
            key, raw = line.split("=", 1)
            existing[key.strip()] = raw.strip()

    existing.update(values)

    lines = [
        "# Auto-generated by auth.py. Do not share this file.",
        f"CLAUDE_ORG_ID={existing.get('CLAUDE_ORG_ID', '')}",
        f"CLAUDE_COOKIE_HEADER={existing.get('CLAUDE_COOKIE_HEADER', '')}",
        f"ANTHROPIC_DEVICE_ID={existing.get('ANTHROPIC_DEVICE_ID', '')}",
        f"ANTHROPIC_ANONYMOUS_ID={existing.get('ANTHROPIC_ANONYMOUS_ID', '')}",
        _env_line(existing, "POLL_INTERVAL_SECONDS", "60"),
        _env_line(existing, "DASHBOARD_HOST", "127.0.0.1"),
        _env_line(existing, "DASHBOARD_PORT", "7474"),
        _env_line(existing, "AUTH_BROWSER", "chrome"),
        _env_line(existing, "EXPECTED_WEEKLY_LINE_ENABLED", "true"),
        _env_line(existing, "EXPECTED_ACTIVE_START_HHMM", "08:00"),
        _env_line(existing, "EXPECTED_ACTIVE_END_HHMM", "19:00"),
    ]

    Path(RUNTIME_ENV_PATH).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _env_line(existing: dict[str, str], key: str, default: str) -> str:
    return f"{key}={existing.get(key, default)}"


def _launch_auth_browser(playwright: Any, auth_browser: str, logger: logging.Logger) -> Any:
    browser_name = auth_browser.strip().lower()
    profile_dir = BROWSER_PROFILE_DIR / browser_name
    profile_dir.mkdir(parents=True, exist_ok=True)

    if browser_name == "chrome":
        try:
            logger.info("Launching auth browser: chrome")
            return playwright.chromium.launch_persistent_context(
                user_data_dir=str(profile_dir),
                channel="chrome",
                headless=False,
                viewport={"width": 1280, "height": 900},
            )
        except Exception as exc:
            logger.warning("Chrome launch failed, falling back to Chromium: %s", exc)
            browser_name = "chromium"
            profile_dir = BROWSER_PROFILE_DIR / browser_name
            profile_dir.mkdir(parents=True, exist_ok=True)

    browser_type = getattr(playwright, browser_name)
    logger.info("Launching auth browser: %s", browser_name)
    try:
        return browser_type.launch_persistent_context(
            user_data_dir=str(profile_dir),
            headless=False,
            viewport={"width": 1280, "height": 900},
        )
    except Exception as exc:
        if not _looks_like_missing_browser_binary(exc):
            raise
        logger.warning(
            "Browser %s is not installed for Playwright, attempting automatic install: %s",
            browser_name,
            exc,
        )
        _install_playwright_browser(browser_name, logger)
        return browser_type.launch_persistent_context(
            user_data_dir=str(profile_dir),
            headless=False,
            viewport={"width": 1280, "height": 900},
        )


def _install_playwright_browser(browser_name: str, logger: logging.Logger) -> None:
    subprocess.run(
        [sys.executable, "-m", "playwright", "install", browser_name],
        check=True,
    )
    logger.info("Installed Playwright browser: %s", browser_name)


def _looks_like_missing_browser_binary(exc: Exception) -> bool:
    text = str(exc).lower()
    return (
        "executable doesn't exist" in text
        or "browser has been closed" in text and "install" in text
        or "please run the following command" in text
    )
