// Tests for the burn-rate math in web.py.
//
// Run: ./scripts/run_tests.sh   (regenerates shipped.mjs from web.py first)
//
// shipped.mjs is generated by extract_js.py and holds the real function bodies
// from web.py, so these assert against shipped code rather than a copy that
// could drift.

import test from 'node:test';
import assert from 'node:assert/strict';
import {
  seriesFor, computeBurnRate, currentBurn, fmtBurn, setViewMode,
} from './shipped.mjs';

const MIN = 60_000;
const T0 = Date.UTC(2026, 6, 16, 10, 0, 0);
// Build rows the way the /data.json payload does: ts plus per-window percentages.
const rows = (pairs) => pairs.map(([min, pct]) => ({
  ts: new Date(T0 + min * MIN).toISOString(), session_pct: pct, weekly_pct: pct,
}));
const burnOf = (r) => computeBurnRate(r, seriesFor(r, 'session_pct'));
// Slopes accumulate float error, so compare with a tolerance rather than ===.
const closeTo = (actual, expected) => assert.ok(
  Math.abs(actual - expected) < 1e-9, `expected ~${expected}, got ${actual}`,
);

test.beforeEach(() => setViewMode('raw'));

test('steady climb reads as a constant slope', () => {
  // +0.1%/min = 6 %/hr.
  closeTo(burnOf(rows([[0, 40], [1, 40.1], [2, 40.2]])).at(-1), 6);
});

test('flat usage reads as zero, not null', () => {
  closeTo(burnOf(rows([[0, 40], [1, 40], [2, 40]])).at(-1), 0);
});

test('a reset reads as a gap, never a negative spike', () => {
  const burn = burnOf(rows([[0, 90], [1, 95], [2, 3]]));
  assert.equal(burn.at(-1), null);
  assert.ok(burn.every((v) => v === null || v >= 0));
});

test('current burn does not walk back past a reset to a stale slope', () => {
  // Regression: lastNonNull() reported the pre-reset climb as if it were live.
  const burn = burnOf(rows([[0, 90], [1, 95], [2, 3]]));
  assert.equal(currentBurn(burn), null);
  assert.equal(fmtBurn(currentBurn(burn)), '-');
});

test('step weights are clipped to the trailing window', () => {
  // The 10-40min step only overlaps the [20,50] window by 20 of its 30 minutes.
  // Unclipped this averages to 52.5; clipped it is 50.
  closeTo(burnOf(rows([[0, 40], [10, 50], [40, 80], [50, 85]])).at(-1), 50);
});

test('burn rate follows the view-mode selector', () => {
  // One isolated spike: reads as a ~10x slope climbing, then its recovery trips
  // the drop check and blanks the window. Cleaning should remove both effects.
  const spiky = rows([[0, 40], [1, 40.1], [2, 40.2], [3, 40.3],
    [4, 40.4], [5, 45], [6, 40.5], [7, 40.6]]);

  setViewMode('raw');
  const raw = burnOf(spiky);
  assert.ok(raw.some((v) => v > 20), 'raw should surface the spike as-is');
  assert.ok(raw.slice(1).includes(null), 'raw should show the false-reset gap');

  for (const mode of ['clean', 'smooth']) {
    setViewMode(mode);
    const out = burnOf(spiky);
    assert.ok(out.every((v) => v === null || v < 20), `${mode} should damp the spike`);
    assert.ok(!out.slice(1).includes(null), `${mode} should have no false reset`);
  }
});

test('output is aligned 1:1 with rows', () => {
  const r = rows([[0, 40], [1, 41], [2, 42]]);
  assert.equal(burnOf(r).length, r.length);
  assert.equal(burnOf(r)[0], null, 'first sample has no preceding step');
});

test('degenerate input does not throw', () => {
  assert.deepEqual(computeBurnRate([], []), []);
  assert.deepEqual(computeBurnRate(rows([[0, 1]]), [1]), [null]);
  const nulls = rows([[0, null], [1, null]]);
  assert.ok(computeBurnRate(nulls, [null, null]).every((v) => v === null));
});

test('fmtBurn renders missing values as a dash', () => {
  for (const v of [null, undefined, NaN]) assert.equal(fmtBurn(v), '-');
  assert.equal(fmtBurn(4.25), '4.3 %/hr');
});
