"""Extract named JS functions verbatim from web.py for testing.

The dashboard's JS lives inside a Python string in web.py, so there is nothing
for node to import. Rather than keep a hand-copied duplicate in the test file
(which silently rots the moment web.py changes), pull the function text straight
out of the source by brace-matching. The tests then exercise shipped code.

Usage: python scripts/extract_js.py > scripts/shipped.mjs
"""

import pathlib
import re
import sys

WEB_PY = pathlib.Path(__file__).resolve().parent.parent / "web.py"

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from config import BURN_WINDOW_MINUTES

# Everything computeBurnRate transitively needs, plus the view-mode pipeline it
# now reads through, plus buildResetTraces and the two helpers it leans on.
FUNCTIONS = [
    "cleanIsolated",
    "smoothMoving",
    "seriesFor",
    "computeBurnRate",
    "currentBurn",
    "fmtBurn",
    "pad2",
    "toLocalPlotTs",
    "buildResetTraces",
]

# buildResetTraces walks this, and the order it declares is the trace order the
# legend persistence indexes into.
CONSTS = ["RESET_MARKER_SERIES"]


def _match_delimiters(src: str, start: int, opener: str, closer: str, name: str) -> str:
    depth = 0
    for i in range(start, len(src)):
        if src[i] == opener:
            depth += 1
        elif src[i] == closer:
            depth -= 1
            if depth == 0:
                return src[:i + 1]
    sys.exit(f"extract_js: unbalanced {opener}{closer} in {name}")


def extract(src: str, name: str) -> str:
    match = re.search(r"^function %s\s*\(" % re.escape(name), src, re.M)
    if not match:
        sys.exit(f"extract_js: function not found in web.py: {name}")
    start = src.index("{", match.start())
    return _match_delimiters(src, start, "{", "}", name)[match.start():]


def extract_const(src: str, name: str) -> str:
    match = re.search(r"^const %s\s*=\s*\[" % re.escape(name), src, re.M)
    if not match:
        sys.exit(f"extract_js: const not found in web.py: {name}")
    start = src.index("[", match.start())
    return _match_delimiters(src, start, "[", "]", name)[match.start():] + ";"


def main() -> None:
    src = WEB_PY.read_text()
    parts = [
        "// GENERATED by scripts/extract_js.py -- do not edit.",
        "// Function bodies are copied verbatim from web.py.",
        "",
        "// seriesFor reads this module-global in web.py; the tests set it.",
        'let viewMode = "raw";',
        "export function setViewMode(mode) { viewMode = mode; }",
        "// computeBurnRate reads this module-global in web.py, where it is",
        "// templated from config.BURN_WINDOW_MINUTES. Keep them in sync.",
        f"const BURN_WINDOW_MINUTES = {BURN_WINDOW_MINUTES};",
        "// buildResetTraces reads this module-global in web.py, where it is",
        "// seeded from localStorage; the tests set it.",
        "const resetMarkerShown = {};",
        "export function setResetMarkerShown(key, shown) { resetMarkerShown[key] = shown; }",
    ]
    parts += [extract_const(src, name) for name in CONSTS]
    parts += [extract(src, name) for name in FUNCTIONS]
    parts.append("export { %s };" % ", ".join(FUNCTIONS + CONSTS))
    print("\n\n".join(parts))


if __name__ == "__main__":
    main()
