"""Extract named JS functions verbatim from web.py for testing.

The dashboard's JS lives inside a Python string in web.py, so there is nothing
for node to import. Rather than keep a hand-copied duplicate in the test file
(which silently rots the moment web.py changes), pull the function text straight
out of the source by brace-matching. The tests then exercise shipped code.

Usage: python scripts/extract_js.py > scripts/shipped.mjs
"""

import pathlib
import re
import sys

WEB_PY = pathlib.Path(__file__).resolve().parent.parent / "web.py"

# Everything computeBurnRate transitively needs, plus the view-mode pipeline it
# now reads through.
FUNCTIONS = [
    "cleanIsolated",
    "smoothMoving",
    "seriesFor",
    "computeBurnRate",
    "currentBurn",
    "fmtBurn",
]


def extract(src: str, name: str) -> str:
    match = re.search(r"^function %s\s*\(" % re.escape(name), src, re.M)
    if not match:
        sys.exit(f"extract_js: function not found in web.py: {name}")
    start = src.index("{", match.start())
    depth = 0
    for i in range(start, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return src[match.start() : i + 1]
    sys.exit(f"extract_js: unbalanced braces in {name}")


def main() -> None:
    src = WEB_PY.read_text()
    parts = [
        "// GENERATED by scripts/extract_js.py -- do not edit.",
        "// Function bodies are copied verbatim from web.py.",
        "",
        "// seriesFor reads this module-global in web.py; the tests set it.",
        'let viewMode = "raw";',
        "export function setViewMode(mode) { viewMode = mode; }",
    ]
    parts += [extract(src, name) for name in FUNCTIONS]
    parts.append("export { %s };" % ", ".join(FUNCTIONS))
    print("\n\n".join(parts))


if __name__ == "__main__":
    main()
